server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: "gin_logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "gin_logs"
          __path__: ./gin_logs.log 
